version: "3.8"
services:
    rhasspy:
        image: "rhasspy/rhasspy"
        container_name: rhasspy
        restart: unless-stopped
        network_mode: host
        volumes:
            - "./rhasspy/profiles:/profiles"
            - "/etc/localtime:/etc/localtime:ro"
        devices:
            - "/dev/snd:/dev/snd"
        command: --user-profiles /profiles --profile de
    hermes-led:
        container_name: hermes-led
        image: thund/hermes-led:0.0.2
        network_mode: host
        volumes:
            - ./rhasspy/profiles/de:/tmp/rhasspy
        environment:
            - "TZ=Europe/Berlin"
            - "HLC_ARGUMENTS=--hardware=respeaker4 --pathToConfig=/tmp/rhasspy/profile.json --engine=rhasspy --mqttServer=127.0.0.1"
        devices:
            - /dev/gpiomem:/dev/gpiomem
            - /dev/mem:/dev/mem
            - /dev/spidev0.0:/dev/spidev0.0
            - /dev/spidev0.1:/dev/spidev0.1
        restart: unless-stopped
        privileged: true
